[package]
name = "model"
version = "0.1.0"
edition = "2024"

[dependencies]
linfa = "0.6.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
axum = "0.7"
tokio = { version = "1.36", features = ["full"] }
dotenvy = "0.15"